### ISSUE TITLE
iOS - Some ad and tracking calls evading ad blocking & tracking protection shields

### ISSUE THREAD

**Issue by lukemulks** [brave/ad-block#44] opened 2017-01-11 02:10 UTC
Moving the iOS blocking issues to this repro for further investigation as advised from the response to the issue filed yesterday. ( https://github.com/brave/browser-ios/issues/647 )

After running some benchmark testing across a handful of domains, we observed quite a few ad and tracking calls being made over network traffic in iOS, that should be covered by Brave ad blocking and tracking protection shields. 

These instances only appeared to occur in iOS, as Android was blocking all the ad and tracking requests from the same domain. 

Testing took place from an iPad 2 and iPhone 6, both using Brave v1.2.19
Comparisons in Android took place from Nexus 5 (phone) and Nexus 9 (tablet) devices, both running versions 1.0.7, 1.0.8 and 1.0.9 during different test phases. 

To rule out anti-ad blockers, and to ensure that what was observed was not due to errors in recording and capturing the sessions, I put a lot of time in yesterday and Sunday night to meticulously perform the following checks:

*Check 1: Shields Up & Down traffic comparison checks for iOS devices*
>-All iOS Shields Down and Shields Up session captures for iOS and Android were reviewed for benchmarking domains tested, to check and determine the degree of ad blocking and tracking protection taking place with shields up.
_Result:_ It was determined that _some_ blocking was taking place as expected, but not all. Ad/tracking events that were observed with shields up were pulled and noted from iPhone and iPad session captures.

*Check 2: Safari Comparisons*
>-An additional check was performed against Safari traffic captured from iPad benchmark testing, and compared against Shields Up & Down captures from the iPad.
_Result:_ iOS Shields Down captures aligned with Safari as expected. Blocking variances were observed in iPad Shields Up session captures as noted above.

*Check 3: iOS Shields Up ad/tracking event list compared against Android Shields Up/Down captures from the same benchmark testing domains*
>-Every iOS ad/tracking event that was pulled and listed from the steps above was checked against both Shields Up and Down session captures for Android tablet and phone. 
>
>-There were two instances where two domains appeared to be using (weak) anti-ad blockers with varying levels of effectiveness in iOS and Android. Those ad/tracking events were removed from the list, and will be filed as a separate anti-ad blocking issue from this one.

What remains, is the list below of ad and tracking events that were observed from both the iPad and iPhone with Brave Shields up on the following domains: 

- https://www.hollywood.com
- https://www.ktla.com
- https://www.technobuffalo.com
- https://www.tmz.com

I've included which blocking list the ad and tracking events that got past iOS blocking shields are listed on for easy reference: 

- scorecardresearch.com (disconnect.me)
- imrworldwide.com (disconnect.me)
- google-analytics.com (disconnect.me)
- googletagservices.com (disconnect.me, easylist)
- googlesyndication.com (disconnect.me, easylist)
- quantserve.com (disconnect.me)
- teads.tv (disconnect.me, easylist) 
- netshelter.net (disconnect.me, easylist)
- viglink.com (disconnect.me, easylist)
- bluekai.com (disconnect.me)
- bkrtx.com (disconnect.me)
- dynamicyield.com (easylist)
- truste.com (disconnect.me, easylist)
- tubemogul.com (disconnect.me, easylist)
- sitescout.com (disconnect.me, easylist)
- sharethrough.com (easylist)

I'm not sure why Android shields are blocking the above domains, but iOS shields are letting them get by. There is some blocking successfully taking place in iOS, but I don't know exactly why it's not matching Android. 

Is there any chance that the update to move the blocking and tracking shields within the brave org acct could have caused what has been observed, if it took place between iOS app market release updates? 

I can provide CSV exports from the traffic sessions captured if that would be helpful as well.

**Comment by bbondy** [comment] 2017-01-11 13:12
> Is there any chance that the update to move the blocking and tracking shields within the brave org acct could have caused what has been observed, if it took place between iOS app market release updates?

No.

**Comment by bbondy** [comment] 2017-01-11 13:18
To check something against adblock these pieces of information are needed:
1. The full URL that was loaded into the browser
2. The full URL of the subresource that you expect to be blocked
3. What type of subresource was it, iframe, image, etc.

Adblock works not only on host names but also portions of URL paths, query parameters, etc. Some rules are only specific to images, some rules only block on a one domain but no others, some rules block on all domains except for particular ones. 

Note that for tracking protection which is tracked at github.com/brave/tracking-protection only the first 2 of these are needed and only the host names.

Bugs should be tracked in this repo once you use the util.js tool to confirm that something that you think should be blocked is actually not being blocked. https://github.com/brave/ad-block#util-for-checking-urls 

It would also be helpful to see which rule you think should be blocking it but isn't.  

From the above it seems like this is probably a problem with tracking protection not working on iOS but I'll look into it now.

**Comment by bbondy** [comment] 2017-01-11 13:50
@lukemulks thanks for taking the time to do this investigation by the way.  The investigation you did by the way is very helpful, the above is just added suggestions to diagnose further for the future.

@garvankeeley if these domains are getting through then tracking protection isn't working on iOS. I posted this issue to track that here: https://github.com/brave/browser-ios/issues/649

@lukemulks w.r.t. the adblock ones:

- googletagservices.com: not enough information given to tell, the EasyList rules involves more than just the hostname

- googlesyndication.com: not enough information given to tell, the EasyList rules involves more than just the hostname

- teads.tv: this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||teads.tv^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://teads.tv`.  Being tracked here: https://github.com/brave/browser-ios/issues/650

- netshelter.net: this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||netshelter.net^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://netshelter.net`.  Being tracked here: https://github.com/brave/browser-ios/issues/650

- viglink.com: not enough information given to tell, the EasyList rules involves more than just the hostname

- dynamicyield.com: not enough information given to tell, the EasyList rules involves more than just the top level hostname

- truste.com: not enough information given to tell, the EasyList rules involves more than just the top level hostname

- tubemogul.com:  this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||tubemogul.com^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://tubemogul.com`.  Being tracked here: https://github.com/brave/browser-ios/issues/650

- sitescout.com:  this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||sitescout.com^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://sitescout.com`. Being tracked here: https://github.com/brave/browser-ios/issues/650

- sharethrough.com:   this has a generalized rule for just the host name so that is enough to diagnose this one.  The EasyList rule in question is: `||sharethrough.com^$third-party` and using check.js, it reports matching true which means it should be blocked. `node scripts/check.js  --host www.cnet.com --location https://sharethrough.com`.  Being tracked here: https://github.com/brave/browser-ios/issues/650

Since it seems like there is no bug detected yet in the library, and the details were worked out into where the problem is, there's nothing left to do here. So closing this one.  Thanks again for the report and investigation.

**Closed by bbondy** 2017-01-11 13:50 UTC
Labels: bug, help wanted
