### ISSUE TITLE
Need block html element in webpage , like ublock origin

### ISSUE THREAD

**Issue by netroby** [brave/ad-block#230] opened 2019-12-31 06:26 UTC
Brave ad block weakness. not always block ads. 
So current i using firefox, it has the ublock origin , which really can block all the ads.

See one example ad block rules

```
cnbeta.com##.cbv810
cnbeta.com##.cbv:not(#cb_share)
```
it will block an html element which has class name `cbv810`, and `cbv` not id equals `cb_share`

I love brave browser, but due to many ads, i can not using brave as primary browser. 

I should using firefox for clean surfing

**Comment by snyderp** [comment] 2019-12-31 15:00
Hi @netroby.

Thanks for the issue.  A couple of replies
1) this project isn't used any more. Adblocking in brave is now handled by https://github.com/brave/adblock-rust
2) We expect to be shipping cosmetic blocking like you describe very soon, once https://github.com/brave/brave-browser/issues/5381 is merged

**Comment by snyderp** [comment] 2019-12-31 15:00
I'm going to close this as a dupe of https://github.com/brave/brave-browser/issues/5381, but if you don't see a fix shipping in dev in the next few weeks, feel free to reopen

**Closed by snyderp** 2019-12-31 15:00 UTC
