### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by ballo** [brave/ad-block#228] opened 2019-12-06 21:24 UTC
This filter doesn't work in Brave (OSX version, if that matters):
ebay.com#@#li.s-item:-abp-has(span:-abp-contains(SPONSORED)) 
Works fine in µBlock Origin for Chromium

**Comment by snyderp** [comment] 2019-12-06 22:50
Howdy @ballo 

We don't currently ship / support cosmetic filters, though we will soon (no promises but we hope it'll go into nightly shortly).  You can follow the issue here https://github.com/brave/brave-browser/issues/5381

Until Brave enables cosmetic filtering, rules like the above definitely won't work.  But even when cosmetic filtering goes live, we don't currently support all of the ABP additions to filter rules.  We have an issue to support them here https://github.com/brave/adblock-rust/issues/59, though we expect that adding support for the above, procedurally enforced style of rules will be low priority for a while.

Closing this as a dupe of https://github.com/brave/adblock-rust/issues/59.  Thanks for the issue!

**Closed by snyderp** 2019-12-06 22:50 UTC
